openapi: 3.0.0
info:
  title: Simple API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get list of users
    post:
      summary: Create a new user
  /users/{id}:
    get:
      summary: Get a user by ID
