openapi: 3.0.0
info:
  title: Simple API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get list of users
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
          example: 2
  /users/{id}:
    get:
      summary: Get a user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 42
